name: Convert Notebooks to PDF

on:
  push:
    paths:
      - 'notebooks/**/*.ipynb'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    ## FIX
    - name: Install system dependencies (Pandoc & LaTeX)
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic

    - name: Install Python dependencies
      run: |
        pip install nbconvert

    - name: Convert notebooks to PDF
      run: |
        jupyter nbconvert --to pdf notebooks/*.ipynb

    - name: Upload PDFs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pdf-notebooks
        path: notebooks/*.pdf